### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-gazebo-ros-control#1]
Package fails to build since ignition-transport fails to build somewhere along the line

**Comment by acxz** [comment]
Using `libpgm-git` instead of `libpgm` successfully installs ignition-transport and therefore this package also builds fine.

**Comment by jwhendy** [comment]
Adding here for no particular reason as there are a bunch of these ignition issues. I hadn't been bitten by this and just wanted to add that some unknown sequence of rebuild attempts finally worked. I really don't know what happened. I did `makepkg` on all the `ignition-foo-n` local packages I had, including doing `git clone` just in case they changed, built, installed, reinstalled, rebuilt... no idea.

Ultimately I removed `ignition-transport-4` (which removed protobuf, protobuf-c, zeromq and a few others) and rebuilt. It worked. No idea, but that was extremely frustrating. The errors look like this, should anyone else stumble on this:
```
/usr/include/ignition/msgs1/ignition/msgs/material.pb.h:182:30: error: ‘google::protobuf::uint8* ignition::msgs::Material_Script::InternalSerializeWithCachedSizesToArray(google::protobuf::uint8*) const’ marked ‘final’, but is not virtual
  182 |   ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/ignition/msgs1/ignition/msgs/material.pb.h:329:8: error: ‘bool ignition::msgs::Material::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)’ marked ‘final’, but is not virtual
  329 |   bool MergePartialFromCodedStream(
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/ignition/msgs1/ignition/msgs/material.pb.h:332:8: error: ‘void ignition::msgs::Material::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const’ marked ‘final’, but is not virtual
  332 |   void SerializeWithCachedSizes(
      |        ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/ignition/msgs1/ignition/msgs/material.pb.h:334:30: error: ‘google::protobuf::uint8* ignition::msgs::Material::InternalSerializeWithCachedSizesToArray(google::protobuf::uint8*) const’ marked ‘final’, but is not virtual
  334 |   ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
```
